import localFonts from 'next/font/local'
import "./globals.css";



const general = localFonts({
  src: [
    { path: '/fonts/general.woff2', weight: '400', style: 'normal'},
   
  ],
  variable: '--general',

});




export const metadata = {
  title: "Awwward",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` ${general.variable}  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
